## welcome gist
### welcome apssdc

# python
- introduction
- data stuctures
- data types
- fun
- files
- Regular expresions
- pandas
- numpy


<img src="images.jpg">
[google]

In [1]:
## numpy
- numerical python 
- it works as data


SyntaxError: invalid syntax (<ipython-input-1-fa793b6f13f3>, line 2)

In [6]:
## creating numpy array
import numpy as np
a=np.array([1,2,3,4,5])
a



array([1, 2, 3, 4, 5])

In [7]:
a.shape

(5,)

In [8]:
a.ndim

1

In [9]:
a2=np.array([[1,2,3,4],[1,3,4,5,],[4,5,6,7]])
a2

array([[1, 2, 3, 4],
       [1, 3, 4, 5],
       [4, 5, 6, 7]])

In [10]:
a2[0:1:3]

array([[1, 2, 3, 4]])

In [11]:
a2[0:2]

array([[1, 2, 3, 4],
       [1, 3, 4, 5]])

In [12]:
a2[1:4]

array([[1, 3, 4, 5],
       [4, 5, 6, 7]])

In [13]:
a2[1:4,2:3]

array([[4],
       [6]])

In [14]:
np.random.randint(1,20,50)

array([11, 17,  4,  8,  6, 14, 18, 17, 10,  2, 18, 13, 17,  3, 16, 11,  5,
       11, 10,  9,  7, 10, 14,  4, 10, 14, 12, 19, 18, 14, 19, 17, 14, 13,
        1, 11, 12, 13,  1, 18, 13, 17, 15,  4,  5,  4,  6,  1, 19,  1])

In [15]:
a2

array([[1, 2, 3, 4],
       [1, 3, 4, 5],
       [4, 5, 6, 7]])

In [16]:
a2

array([[1, 2, 3, 4],
       [1, 3, 4, 5],
       [4, 5, 6, 7]])

In [17]:
a2.reshape(2,6)

array([[1, 2, 3, 4, 1, 3],
       [4, 5, 4, 5, 6, 7]])

In [18]:
print(len(dir(np)))

620


In [19]:
a2=np.arange(1,50)

In [20]:
a2[a2%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [21]:
a2.size

49

In [22]:
a2.reshape(7,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [23]:
a=np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [24]:
e=a.reshape(3,10)
e

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [25]:
e[0:3:2,1:9:7]

array([[ 2,  9],
       [22, 29]])

In [26]:
np.ones([3,5],int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.vstack(e,a2)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [28]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [29]:
np.linspace(1,29.90)

array([ 1.        ,  1.58979592,  2.17959184,  2.76938776,  3.35918367,
        3.94897959,  4.53877551,  5.12857143,  5.71836735,  6.30816327,
        6.89795918,  7.4877551 ,  8.07755102,  8.66734694,  9.25714286,
        9.84693878, 10.43673469, 11.02653061, 11.61632653, 12.20612245,
       12.79591837, 13.38571429, 13.9755102 , 14.56530612, 15.15510204,
       15.74489796, 16.33469388, 16.9244898 , 17.51428571, 18.10408163,
       18.69387755, 19.28367347, 19.87346939, 20.46326531, 21.05306122,
       21.64285714, 22.23265306, 22.82244898, 23.4122449 , 24.00204082,
       24.59183673, 25.18163265, 25.77142857, 26.36122449, 26.95102041,
       27.54081633, 28.13061224, 28.72040816, 29.31020408, 29.9       ])

In [30]:
np.full(15,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [31]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [32]:
np.split(a,5)

[array([1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18]),
 array([19, 20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29, 30])]

In [33]:
                                                                                                                             n                                                          /

SyntaxError: invalid syntax (<ipython-input-33-b46a9be13ae4>, line 1)

In [34]:
a.max()

30

In [35]:
a2.min()

1

In [36]:
e.diagonal()

array([ 1, 12, 23])

In [37]:
e.T

array([[ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29],
       [10, 20, 30]])

In [38]:
e.transpose()

array([[ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29],
       [10, 20, 30]])

In [39]:
e.mean()

15.5

e.mode()

In [43]:
np.median(a)

15.5

In [44]:
np.percentile(a,20)

6.800000000000001

TypeError: 'module' object is not callable